### PR TITLE
Update Client.js

### PR DESCRIPTION
**Pull request by jalric**
getAppEnv method return now user API token.
Close zenaton/agent#333

### CODE REVIEW

**Comment by Ciboulette** [comment]
Why the CI is broken?

**Comment by jalric** [comment]
Because some tests use `getAppEnv`method and don't expect to get an apiToken in the response.

We can:
1. fix the tests
2. add a getApiToken method (and add a test).

The second solution seems to me more secure. I don't like the idea to return too often API credentials in many part of the code. Agree with that?

**Review by Ciboulette — COMMENTED** [review]
Changelog missing

**Comment by jalric** [comment]
Changelog updated

**Review by Ciboulette — APPROVED** [review]

**Comment by pylebecq** [comment]
What do we do with this PR? Should it be included in the next release?

**Pull request closed without merging**
